#!/bin/sh
#
# exampled: sample daemon
#
# chkconfig:   2345 26 89
# description: example daemon

. /etc/rc.d/init.d/functions

start()
{
    echo -n $"Starting exampled: "
    daemon /usr/bin/exampled &
    touch /var/lock/subsys/exampled
    echo
}

stop()
{
    echo -n $"Shutting down exampled: "
    killproc exampled
    rm -f /var/lock/subsys/exampled
    echo
}

[ -f /usr/bin/exampled ] || exit 0

# see how we were called
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  condrestart)
        [ -e /var/lock/subsys/exampled ] && (stop; start)
        ;;
  status)
        status exampled
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|condrestart}"
        exit 1
esac

exit 0
